# Generated by Django 2.1.3 on 2018-12-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='city_name',
        ),
    ]
