# Generated by Django 2.1.3 on 2018-11-27 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineProp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id_no', models.IntegerField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=50)),
                ('s_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineProp.State')),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id_no', models.IntegerField(primary_key=True, serialize=False)),
                ('loc_name', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineProp.City')),
            ],
        ),
        migrations.CreateModel(
            name='Property_name',
            fields=[
                ('id_no', models.IntegerField(primary_key=True, serialize=False)),
                ('loc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineProp.Locality')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField()),
                ('email_id', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('contact_no', models.IntegerField()),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
