# Generated by Django 2.1.1 on 2018-12-01 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineProp', '0002_city_locality_property_name_sales_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField()),
                ('email_id', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineProp.City')),
            ],
        ),
    ]
